CREATE TABLE DC_CHARACTER(
    CHARACTER_ID INT PRIMARY KEY,
    CHARACTER_NAME VARCHAR2(100) UNIQUE,
    CHARACTER_AGE INT,
    CHARACTER_POWERS VARCHAR2(4000)
);
/
INSERT INTO DC_CHARACTER (CHARACTER_NAME, CHARACTER_AGE, CHARACTER_POWERS) VALUES ('The Flash', 25, 'Super speed, time travel');
INSERT INTO DC_CHARACTER (CHARACTER_NAME, CHARACTER_AGE, CHARACTER_POWERS) VALUES ('Batman', 40, 'None');
INSERT INTO DC_CHARACTER (CHARACTER_NAME, CHARACTER_AGE, CHARACTER_POWERS) VALUES ('Green Lantern', 26, 'Ring of willpower');
INSERT INTO DC_CHARACTER (CHARACTER_NAME, CHARACTER_AGE, CHARACTER_POWERS) VALUES ('Superman', 25, 'God');
INSERT INTO DC_CHARACTER (CHARACTER_NAME, CHARACTER_AGE, CHARACTER_POWERS) VALUES ('Aquaman', 25, 'Talks to fish');
CREATE SEQUENCE SQ_DC_CHAR_PK
START WITH 1
INCREMENT BY 1;
/

--TRIGGERS
CREATE TRIGGER TR_DC_CHAR
BEFORE INSERT ON DC_CHARACTER
FOR EACH ROW
BEGIN
    SELECT SQ_DC_CHAR_PK.NEXTVAL INTO :NEW.CHARACTER_ID FROM DUAL;
END;
/

select * from DC_CHARACTER